# GGplot2 cheatsheet

Yiqin Shi and Yuxuan Liang

GGplot2 is one of the most commonly used plotting packages, which can efficiently create complex and aesthetically pleasing graphics using easily understandable syntax. The purpose of this cheatsheet is to provide you with organized information about package GGplot2. This cheatsheet consists of two parts. The first part is the classification of graphics. The second part is the customization of graph drawing. The classification in the cheat sheet are made according to the website https://r-charts.com/#category. For the first part, there are function codes, along with suggestions for when to use it, sample diagrams, and some useful argument or function notes for each category. For the second part, this cheatsheet contains different customization methods for drawing graphics with examples that will help you better understand their roles.

The cheatsheet can be accessed through the following link:
https://github.com/yxliv/communitycontribution/blob/main/communitycontribution.pdf
