# R Shiny and Interactive Map Tutorial

Yarong Wang and Qian Zhang

## Description

This is an R shiny and its interactive map tutorial that includes a brief introduction to R shiny, the basic steps and components to make an R shiny app, step-by-step instructions for making an interactive map using the package `leaflet` as well as adding certain features to the map, and finally the integration of the `leaflet` package with R shiny. 

To see the details of this tutorial, please go to the link provided below.

## Link

[Please click the link to access the tutorial.](https://github.com/yrwang1/GR5293-Statistical-Graphics-Community-Contribution)

## References

1. [Application layout guide](https://shiny.rstudio.com/articles/layout-guide.html)

2. [Shiny Widgets Gallery](https://shiny.rstudio.com/gallery/widget-gallery.html)

3. [R shiny cheatsheet](https://shiny.rstudio.com/images/shiny-cheatsheet.pdf)

4. [Dataset source for interactive map, complaint cases](https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Current-Year-To-Date-/5uac-w243/data)

5. [Dataset source for interactive map, geographic information](https://data.beta.nyc/dataset/pediacities-nyc-neighborhoods/resource/35dd04fb-81b3-479b-a074-a27a37888ce7)

6. [The modified dataset about complaint cases and the geographic information uploaded to GitHub](https://github.com/QianZhang-Erica/5293-Contribution)
